# https://taskfile.dev
version: "3"

vars:
  CARGO_BIN: ~/.cargo/bin/

tasks:
  install-nextest:
    status:
      - test -f {{.CARGO_BIN}}/cargo-nextest
    cmds:
      - curl -LsSf https://get.nexte.st/latest/linux | tar zxf - -C {{.CARGO_BIN}}

  clone-licenses:
    status:
      - test -d choosealicense.com
    cmds:
      - git clone --depth 1 https://github.com/github/choosealicense.com.git

  check:
    cmds:
      - cargo check --all {{.CLI_ARGS}}

  format:
    cmds:
      - cargo fmt --all {{.CLI_ARGS}}

  lint:
    cmds:
      - cargo clippy --all -- -D clippy::dbg-macro -D warnings

  test:
    deps:
      - install-nextest
    env:
      CLICOLOR_FORCE: "yes"
    cmds:
      - cargo nextest run --no-fail-fast {{.CLI_ARGS}}

  bench:
    deps:
      - clone-licenses
    cmds:
      - cargo bench {{.CLI_ARGS}}

  all:
    - task: format
    - task: check
    - task: lint
    - task: test
