# https://taskfile.dev
version: "3"

tasks:
  check:
    cmds:
      - cargo check --all {{.CLI_ARGS}}

  format:
    cmds:
      - cargo fmt --all {{.CLI_ARGS}}

  lint:
    cmds:
      - cargo clippy --all -- -D clippy::dbg-macro -D warnings

  test:
    cmds:
      - cargo test {{.CLI_ARGS}}

  all:
    - task: format
    - task: check
    - task: lint
    - task: test
